### ISSUE TITLE
Dagger2 remove Dagger 1.x compatible from Module

### ISSUE THREAD

**Issue by ddqd** [techery/presenta#4]
See https://github.com/google/dagger/commit/70f720bc4a25cadfb833194d6c5822fb3c39c6bd

**Comment by almozavr** [comment]
Thanks! Also, there is linked issue to Dagger 2.0 release from Mortar: https://github.com/square/mortar/issues/138
Going to work it out in a few days, the same as to update to latest Flow API update.
